# Generated by Django 4.2.7 on 2024-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='tenchucvu',
            field=models.CharField(db_column='TenChucVu', max_length=20),
        ),
    ]
