# Generated by Django 4.2.7 on 2023-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('idnhanvien', models.AutoField(db_column='IDNhanVien', primary_key=True, serialize=False)),
                ('tennhanvien', models.CharField(db_column='TenNhanVien', max_length=50)),
                ('tenchucvu', models.CharField(db_column='TenChucVu', max_length=50)),
                ('diachi', models.CharField(db_column='DiaChi', max_length=200)),
                ('sdt', models.CharField(db_collation='utf8mb3_general_ci', db_column='SDT', max_length=15)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TaikhoanKhachhang',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tenchucvu',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tennhanvien',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='accountname',
            field=models.CharField(default='Guest', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(db_column='Email', max_length=100, unique=True),
        ),
    ]
