# Generated by Django 4.2.7 on 2024-11-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0002_alter_nhanvien_tenchucvu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nhanvien',
            new_name='GiangVien',
        ),
        migrations.RenameModel(
            old_name='Khachhang',
            new_name='SinhVien',
        ),
    ]
