# Generated by Django 4.2.7 on 2023-12-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0002_nhanvien_delete_taikhoankhachhang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsanpham',
            options={'managed': True},
        ),
    ]
