# Generated by Django 4.2.7 on 2024-11-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0003_rename_nhanvien_giangvien_rename_khachhang_sinhvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='tenchucvu',
            field=models.CharField(db_column='TenChucVu', max_length=25),
        ),
    ]
