# Generated by Django 4.2.7 on 2023-12-14 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0003_alter_reviewsanpham_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsanpham',
            name='id',
            field=models.ForeignKey(db_column='IDUser', default=10000, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewsanpham',
            name='idloaigiay',
            field=models.ForeignKey(db_column='IDLoaiGiay', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='AppGiay.danhmucgiay'),
        ),
    ]
