# Generated by Django 4.2.7 on 2023-12-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0004_reviewsanpham_id_reviewsanpham_idloaigiay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsanpham',
            name='id',
            field=models.ForeignKey(db_column='IDUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewsanpham',
            name='idloaigiay',
            field=models.ForeignKey(db_column='IDLoaiGiay', on_delete=django.db.models.deletion.DO_NOTHING, to='AppGiay.danhmucgiay'),
        ),
    ]
