# Generated by Django 4.2.7 on 2024-11-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0004_alter_giangvien_tenchucvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='email',
        ),
    ]
