# Generated by Django 4.2.7 on 2024-11-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0005_remove_sinhvien_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='nganhhoc',
            field=models.CharField(db_column='NganhHoc', default='DEFAULT VALUE', max_length=30),
        ),
    ]
