# Generated by Django 4.2.7 on 2024-11-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0006_sinhvien_nganhhoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('idlophoc', models.AutoField(db_column='IDLopHoc', primary_key=True, serialize=False)),
                ('tenlophoc', models.CharField(db_column='TenLopHoc', max_length=50)),
                ('mota', models.CharField(db_column='MoTa', default='DEFAULT VALUE', max_length=250)),
                ('cahoc', models.SmallIntegerField(db_column='CaHoc', db_comment=' Ca 1 = 0, Ca 2 = 1, Ca 3 = 2, ...')),
                ('idgiangvien', models.ForeignKey(db_column='IDGiangVien', on_delete=django.db.models.deletion.DO_NOTHING, to='AppGiay.giangvien')),
            ],
            options={
                'db_table': 'lophoc',
                'managed': True,
            },
        ),
    ]
