# Generated by Django 4.2.7 on 2024-11-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0007_lophoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhVienLop',
            fields=[
                ('idthanhvien', models.AutoField(db_column='IDThanhVien', primary_key=True, serialize=False)),
                ('tinhtranghoc', models.SmallIntegerField(db_column='TinhTrangHoc', db_comment='Đang học  = 0, Xin nghỉ  = 1, Không còn học = 2')),
                ('idlophoc', models.ForeignKey(db_column='IDLopHoc', on_delete=django.db.models.deletion.DO_NOTHING, to='AppGiay.lophoc')),
                ('idsinhvien', models.ForeignKey(db_column='IDSinhVien', on_delete=django.db.models.deletion.DO_NOTHING, to='AppGiay.sinhvien')),
            ],
            options={
                'db_table': 'thanhvienlop',
                'managed': True,
            },
        ),
    ]
