# Generated by Django 4.2.7 on 2024-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0008_thanhvienlop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhvienlop',
            name='tinhtranghoc',
            field=models.SmallIntegerField(db_column='TinhTrangHoc', db_comment='Đang xét duyệt = 0, Đang học  = 1, Xin nghỉ  = 2, Không còn học = 3'),
        ),
    ]
