# Generated by Django 4.2.7 on 2024-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0009_alter_thanhvienlop_tinhtranghoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='ngayhoc',
            field=models.SmallIntegerField(db_column='NgayHoc', db_comment=' Thứ 2 = 0, Thứ 3 = 1, Thứ 4 = 2, ...', default=0),
            preserve_default=False,
        ),
    ]
