# Generated by Django 4.2.7 on 2024-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0010_lophoc_ngayhoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhvienlop',
            name='tinhtranghoc',
            field=models.SmallIntegerField(db_column='TinhTrangHoc', db_comment='Đang xét duyệt = 0, Đang học  = 1, Tạm hoãn  = 2, Đã học = 3'),
        ),
    ]
