# Generated by Django 4.2.7 on 2024-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0011_alter_thanhvienlop_tinhtranghoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='mota',
            field=models.CharField(blank=True, db_column='MoTa', max_length=250, null=True),
        ),
    ]
