# Generated by Django 4.2.7 on 2024-12-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0012_alter_lophoc_mota'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='kihoc',
            field=models.CharField(db_column='Ky hoc', default=20990, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lophoc',
            name='maxstudent',
            field=models.SmallIntegerField(db_column='SoSinhVienToiDa', default=100),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='status',
            field=models.SmallIntegerField(db_column='TrangThai', db_comment=' Đang đăng ký = 0, Đang hoạt động = 1, Đã kết thúc = 2, ...', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='nganhhoc',
            field=models.CharField(db_column='NganhHoc', max_length=30),
        ),
    ]
