# Generated by Django 4.2.7 on 2024-12-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0013_lophoc_kihoc_lophoc_maxstudent_lophoc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='status',
            field=models.SmallIntegerField(db_column='TrangThai', db_comment=' Đang đăng ký = 0, Đang hoạt động = 1, Đã kết thúc = 2'),
        ),
    ]
