# Generated by Django 4.2.7 on 2024-12-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0014_alter_lophoc_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lophoc',
            old_name='kihoc',
            new_name='kyhoc',
        ),
    ]
