# Generated by Django 4.2.7 on 2024-12-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0015_rename_kihoc_lophoc_kyhoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lophoc',
            old_name='status',
            new_name='trangthai',
        ),
    ]
