# Generated by Django 4.2.7 on 2024-12-05 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0016_rename_status_lophoc_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='id',
            field=models.ForeignKey(db_column='IDuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='idgiangvien',
            field=models.ForeignKey(db_column='IDGiangVien', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.giangvien'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='id',
            field=models.ForeignKey(db_column='IDuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thanhvienlop',
            name='idlophoc',
            field=models.ForeignKey(db_column='IDLopHoc', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.lophoc'),
        ),
        migrations.AlterField(
            model_name='thanhvienlop',
            name='idsinhvien',
            field=models.ForeignKey(db_column='IDSinhVien', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.sinhvien'),
        ),
    ]
