# Generated by Django 4.2.7 on 2024-12-05 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0017_alter_giangvien_id_alter_lophoc_idgiangvien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='id',
            field=models.ForeignKey(db_column='IDuser', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='id',
            field=models.ForeignKey(db_column='IDuser', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
