# Generated by Django 4.2.7 on 2024-12-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0018_alter_giangvien_id_alter_sinhvien_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonXinNghi',
            fields=[
                ('iddon', models.AutoField(db_column='IDDon', primary_key=True, serialize=False)),
                ('ngayxinnghi', models.DateTimeField(db_column='NgayXinNghi')),
                ('lydo', models.CharField(db_column='Lydo', max_length=300)),
                ('trangthai', models.SmallIntegerField(db_column='TrangThai', db_comment=' Đang xét duyệt = 0, Chấp nhập = 1, Từ chối = 2')),
                ('thoigiangui', models.DateTimeField(db_column='ThoigianGui')),
                ('thoigianphanhoi', models.DateTimeField(db_column='ThoigianPhanhoi')),
                ('idthanhvien', models.ForeignKey(db_column='IDThanhVien', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.thanhvienlop')),
            ],
            options={
                'db_table': 'donxinnghi',
                'managed': True,
            },
        ),
    ]
