# Generated by Django 4.2.7 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0019_donxinnghi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donxinnghi',
            name='thoigianphanhoi',
            field=models.DateTimeField(blank=True, db_column='ThoigianPhanhoi', null=True),
        ),
    ]
