# Generated by Django 4.2.7 on 2024-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0020_alter_donxinnghi_thoigianphanhoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donxinnghi',
            name='ngayxinnghi',
            field=models.DateField(db_column='NgayXinNghi'),
        ),
    ]
