# Generated by Django 4.2.7 on 2024-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0021_alter_donxinnghi_ngayxinnghi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='end_day',
            field=models.DateField(db_column='NgayKetThuc', default='2002-9-8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lophoc',
            name='start_day',
            field=models.DateField(db_column='NgayBatDau', default='2002-9-8'),
            preserve_default=False,
        ),
    ]
