# Generated by Django 4.2.7 on 2024-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0022_lophoc_end_day_lophoc_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='cahoc',
            field=models.SmallIntegerField(db_column='CaHocTrongNgay', db_comment=' Ca 1 = 0, Ca 2 = 1, Ca 3 = 2, ...'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='ngayhoc',
            field=models.SmallIntegerField(db_column='NgayHocTrongTuan', db_comment=' Thứ 2 = 0, Thứ 3 = 1, Thứ 4 = 2, ...'),
        ),
    ]
