# Generated by Django 4.2.7 on 2024-12-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0023_alter_lophoc_cahoc_alter_lophoc_ngayhoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuoiHoc',
            fields=[
                ('idbuoihoc', models.AutoField(db_column='IDbuoiHoc', primary_key=True, serialize=False)),
                ('ngaydienra', models.DateField(db_column='NgayDienRa')),
                ('idlophoc', models.ForeignKey(db_column='IDLopHoc', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.lophoc')),
            ],
            options={
                'db_table': 'buoihoc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('iddiemdanh', models.AutoField(db_column='IDDiemDanh', primary_key=True, serialize=False)),
                ('trangthaidiemdanh', models.SmallIntegerField(db_column='TrangThaiDiemDanh', db_comment=' Có mặt = 0, Muộn học = 1, Vắng có phép = 2, Vắng không có phép = 3')),
                ('thoigianđiemanh', models.DateTimeField(db_column='ThoigianDiemDanh')),
                ('idbuoihoc', models.ForeignKey(db_column='IDBuoiHoc', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.buoihoc')),
                ('idsinhvien', models.ForeignKey(db_column='IDSinhVien', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.sinhvien')),
            ],
            options={
                'db_table': 'diemdanh',
                'managed': True,
            },
        ),
    ]
