# Generated by Django 4.2.7 on 2024-12-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0025_rename_thoigianđiemanh_diemdanh_thoigiandiemdanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiLieuHocTap',
            fields=[
                ('idtailieu', models.IntegerField(db_column='IDTaiLieu', primary_key=True, serialize=False)),
                ('tentailieu', models.CharField(db_column='TenTaiLieu', max_length=100)),
                ('description', models.CharField(db_column='Descriptions', max_length=200, null=True)),
                ('loaitailieu', models.SmallIntegerField(db_column='LoaiTaiLieu', db_comment=' Bài giảng = 0, Bài làm thêm = 1, Video hướng dẫn = 2')),
                ('link', models.CharField(db_column='Link', max_length=255)),
                ('idlophoc', models.ForeignKey(db_column='IDLopHoc', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.lophoc')),
            ],
            options={
                'db_table': 'tailieu',
                'managed': True,
            },
        ),
    ]
