# Generated by Django 4.2.7 on 2024-12-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0027_tailieuhoctap_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailieuhoctap',
            name='file',
        ),
    ]
