# Generated by Django 4.2.7 on 2024-12-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0028_remove_tailieuhoctap_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiTap',
            fields=[
                ('idbaitap', models.IntegerField(db_column='IDBaiTap', primary_key=True, serialize=False)),
                ('tenbaitap', models.CharField(max_length=50)),
                ('mota', models.CharField(db_column='MoTa', max_length=200)),
                ('filebaitap', models.FileField(blank=True, db_column='FileBaiTap', null=True, upload_to='baitap_files/')),
                ('deadline', models.DateTimeField(db_column='HanHop')),
                ('create_day', models.DateTimeField(db_column='NgayTao')),
                ('idlophoc', models.ForeignKey(db_column='IDLopHoc', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.lophoc')),
            ],
            options={
                'db_table': 'baitap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaiLam',
            fields=[
                ('idbailam', models.IntegerField(db_column='IDBaiLam', primary_key=True, serialize=False)),
                ('filebailam', models.FileField(db_column='FileBaiLam', upload_to='nopbai_files/')),
                ('description', models.CharField(blank=True, db_column='MoTa', max_length=200, null=True)),
                ('ngaynop', models.DateTimeField(db_column='NgayNop')),
                ('diem', models.FloatField(blank=True, db_column='DiemSo', null=True)),
                ('idbaitap', models.ForeignKey(db_column='IDBaiTap', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.baitap')),
                ('idsinhvien', models.ForeignKey(db_column='IDSinhVien', on_delete=django.db.models.deletion.CASCADE, to='AppGiay.sinhvien')),
            ],
            options={
                'db_table': 'bailam',
                'managed': True,
            },
        ),
    ]
