# Generated by Django 4.2.7 on 2024-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0029_baitap_bailam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailam',
            name='filebailam',
            field=models.FileField(db_column='FileBaiLam', upload_to='bailam_files/'),
        ),
    ]
