# Generated by Django 4.2.7 on 2024-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0030_alter_bailam_filebailam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baitap',
            name='filebaitap',
            field=models.FileField(db_column='FileBaiTap', default='li', upload_to='baitap_files/'),
            preserve_default=False,
        ),
    ]
