# Generated by Django 4.2.7 on 2024-12-22 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0034_alter_baitap_filebaitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongbBaoTinNhan',
            fields=[
                ('message_id', models.CharField(db_column='IDMessage', max_length=8, primary_key=True, serialize=False)),
                ('receiver_id', models.IntegerField(db_column='IDReceiver')),
                ('message', models.CharField(db_column='NoiDung', max_length=200)),
                ('type', models.SmallIntegerField(db_column='LoaiTinNhan', db_comment='Don nghi hoc = 0, Diểm bài kiểm tra = 1, Ket qua xet đơn nghỉ = 2, Bai tap moi = 3')),
                ('related_id', models.IntegerField(blank=True, db_column='IDLienHe', null=True)),
                ('is_read', models.BooleanField(db_column='DaDoc')),
                ('sender_id', models.ForeignKey(db_column='IDSender', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thongbao',
                'managed': True,
            },
        ),
    ]
