# Generated by Django 4.2.7 on 2024-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGiay', '0035_thongbbaotinnhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongbbaotinnhan',
            name='type',
            field=models.SmallIntegerField(db_column='LoaiTinNhan', db_comment='Don nghi hoc = 0, Diểm bài kiểm tra = 1, Ket qua xet đơn nghỉ = 2, Bai tap moi = 3, Thong bao = 4'),
        ),
    ]
